#
#   _________ __                      .__    .__        
#  /   _____//  |______ _______  _____|  |__ |__|_____  
#  \_____  \\   __\__  \\_  __ \/  ___/  |  \|  \____ \ 
#  /        \|  |  / __ \|  | \/\___ \|   Y  \  |  |_> >
# /_______  /|__| (____  /__|  /____  >___|  /__|   __/ 
#         \/           \/           \/     \/   |__|    

# mcj1m's config 🚀🚀 ---------------------------------------

add_newline = false

format = """
$username [on](white) $directory$cmd_duration 
$character"""

[character]
success_symbol = "[»](bold white)" 
error_symbol = "[»](bold red)"

[username] 
style_user = "blue bold"
style_root = "black bold"
format = "[$user]($style)"  
disabled = false 
show_always = true

[directory] 
style="red"

[dart]
format= "via [ $version] (bold red) "

[cmd_duration]
min_time = 25  
show_milliseconds = false 
disabled = false
style="bold italic #87A752"

# disabled stuff-------------------------------------------

[package] 
disabled = true

[python] 
disabled = true

[rust] 
disabled = true

[aws]
disabled = true

# eof------------------------------------------------------
